# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('himsog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='type',
            new_name='comment_type',
        ),
        migrations.AddField(
            model_name='content',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 24, 13, 31, 0, 388393, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 24, 13, 31, 11, 732571, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
