# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himsog', '0004_remove_comment_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
