# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-29 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himsog', '0007_content_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentimage',
            name='image',
        ),
        migrations.AddField(
            model_name='contentimage',
            name='url',
            field=models.URLField(default='http://placehold.it/1920x1080'),
            preserve_default=False,
        ),
    ]
