# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himsog', '0009_auto_20170129_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='description',
        ),
        migrations.AddField(
            model_name='content',
            name='content1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content3',
            field=models.TextField(null=True),
        ),
    ]
